import {
  Calendar,
  ClipboardCheck,
  Folder,
  FormInput,
  Home,
  Image as ImageIcon,
  LayoutDashboard,
  Lock,
  Newspaper,
  PanelBottom,
  PanelTop,
  Search,
  Send,
  Settings,
  Tag,
  Users,
} from 'lucide-react'

export const NavIcons = {
  Posts: Newspaper,
  Pages: Folder,
  Media: ImageIcon,
  Categories: Tag,
  Settings: Settings,
  Home: Home,
  NewsPage: Newspaper,
  Structure: Users,
  Gallery: ImageIcon,
  Registration: FormInput,
  Login: Lock,
  Header: PanelTop,
  Footer: PanelBottom,
  Users: Users,
  Forms: FormInput,
  Submissions: Send,
  Search: Search,
  Dashboard: LayoutDashboard,
  Acara: Calendar,
  Absensi: ClipboardCheck,
}
